[git]
GITHUB_TOKEN = "github_pat_"

[env]
ENVIRONMENT = "development"

[api]
GEMINI_API = ""
GROQ_API = "gsk_"

[mongodb]
MONGODB_URI = "mongodb://<user:<password>@127.0.0.1:27017/sample-server?authSource=admin&retryWrites=true&w=majority&appName=sample"
DATABASE_NAME = "sample"
